### ISSUE TITLE
support for laravel 4.2.x

### ISSUE THREAD

**Issue by masbenx** [Thatzad/Birder#1]
this package not support for laravel 4.2.x

**Comment by rgomezcasas** [comment]
During this week I'll publish a new version (with a major refactor), framework agnostic, tests...

**Comment by InfiniteDevelopment** [comment]
done? Really wanna use this for a hashtag search.

**Comment by rgomezcasas** [comment]
No, it wasn't done. I'll try to update this. I don't use Laravel anymore, so I'll use you as a tester :P

**Comment by rgomezcasas** [comment]
I just done this commit https://github.com/Thatzad/Birder/commit/be91941e8987c3ebc32cff70fddc539d924e7c0b, tomorrow I'll add tests... Is it working for you?

**Comment by InfiniteDevelopment** [comment]
I will test it now. :) Thanks in advance.

**Comment by InfiniteDevelopment** [comment]
Is this for Laravel 4.2? or 5.x as the commit messages says?

**Comment by InfiniteDevelopment** [comment]
![screen shot 2015-06-02 at 10 34 01 am](https://cloud.githubusercontent.com/assets/1442229/7938328/f2516a86-0912-11e5-88ab-639e2fefb189.png)

This is the screenshot I get.

**Comment by oindypoind** [comment]
This looks like a great package, would be good if it was Laravel 5 compatible.

**Comment by rgomezcasas** [comment]
It's compatible now :P
